/**
*Blog Types
*/

export const BLOG_LOADING = 'BLOG_LOADING';
export const LOAD_BLOG_SUCCESS = 'LOAD_BLOG_SUCCESS';

export const BLOG_LOADING_MUSIC = 'BLOG_LOADING_MUSIC';
export const LOAD_BLOG_MUSIC_SUCCESS = 'LOAD_BLOG_MUSIC_SUCCESS';
